### PR TITLE
feat(UI): uses react-select component

### PR DESCRIPTION
**Pull request by axel7083**
## Description

This PR replace the Select2 custom react component with the `react-select` library.

## Screenshots

| Before | After |
| --- | --- |
| image | image |
| image | image |
| Not searchable | image |
| image | image

## Related issue

Fixes https://github.com/decompme/decomp.me/issues/1152

### CODE REVIEW

**Comment by axel7083** [comment]
@ethteck I do not understand the error of stylelint here :(

**Comment by ethteck** [comment]
I'm not sure.. I can try to take a look later today. the import issue scares me though

**Comment by axel7083** [comment]
> I'm not sure.. I can try to take a look later today. the import issue scares me though

I am feeling like stylelint might be the problem, as I am able to build and run everything locally without issue, plus vercel does not seems to be complaining

**Comment by axel7083** [comment]
Closing as I broke the branch :(

**Pull request closed without merging**
