### PR TITLE
Use Next.js 13 app directory & Tailwind CSS

### LINKED ISSUE #619: Consider using a new CSS architecture
There are a number of issues with the way we do CSS right now: primarily, there is a lot of repeated code for common mixins. Perhaps we should try zero-cost CSS-in-JS such as [vanilla-extract](https://vanilla-extract.style/) or atomic CSS like Tailwind or [unocss](https://uno.antfu.me)/? Alternatively, should we use Sass mixins a lot more?

This might get resolved by virtue of using the Next.js 13 app/ directory and/or #615's consolidated form components, i.e., better componentisation.

### LINKED ISSUE #634: Use allotment instead of react-simple-resizer
https://github.com/johnwalley/allotment

### PR DESCRIPTION
**Pull request by nanaian**
Time for the twice-yearly big design update!

- [x] Add Tailwind (resolves #619)
- [x] New footer
- [x] Adjust navbar (logotype, buttons moved to right)
- [x] Improve the styling of the search box 
- [x] New /settings/account page
- [x] /credits grabs contributors list for this repo from GitHub's API
- [x] Use Next.js 13 app directory for all routes except projects
- [x] Resolve #634
- [x] New welcome page header with scrolling platform icons 

Future, as we get rid of old projects stuff #544:
- Remove any use of the old CSS theme variables (e.g. `--gXXX`, `--aXXX`) in favour of using Tailwind

Future, #307 and #297:
- Reduce variance of UI representations for a Scratch's metadata (see: ScratchList various items)

Screenshots:

<details>
<summary>Logotype in README.md</summary>
image
</details>

<details>
<summary>Homepage</summary>
image
</details>

<details>
<summary>Settings</summary>
image
image
image
</details>

<details>
<summary>Credits</summary>
Those shown with an avatar and an '@' before their username have accounts on the decomp.me instance (so in this screenshot, only I do).
image
</details>

### CODE REVIEW

**Comment by nanaian** [comment]
It appears that next-translate breaks when using the app directory, need to look into that.
Also CI is broken because it uses a too-old Node.js version

**Comment by ethteck** [comment]
Yeah, happy to drop next-translate. we should probably make the new thing such that we could add other languages if we want to, at least. or at the very least, keep it in mind when designing it so it's not too much work to do that.

**Comment by nanaian** [comment]
Working on settings page still, but the rest can be reviewed

**Comment by nanaian** [comment]
react-simple-resizer seems very broken under app/ for whatever reason, need to rethink it

**Comment by ethteck** [comment]
Tested and everything looks great, but I'm getting browser (white) scrollbars on the scratch page rather than the current ones on the live site: 
image

**Comment by nanaian** [comment]
Try this @ethteck? I'm using [color-scheme: dark](https://www.amitmerchant.com/darkmode-aware-scrollbars-using-css/) rather than scrollbar-color as we used before, because then the controls look more native, but it might not work

**Pull request merged**
