### PR TITLE
5.3 C++

### PR DESCRIPTION
**Pull request by LLONSIT**
Implement the ido5.3 c++ translator

### CODE REVIEW

**Comment by mkst** [comment]
Can we set some env var or flag so we don't have to mount a writeable directory from the host?

**Comment by simonlindholm** [comment]
or binding it to the same thing as `/tmp`?

**Comment by simonlindholm** [comment]
No, don't bind /tmp the same broken way. /tmp is already bound! Just do the same thing for /var/tmp as is already done for it.

**Comment by LLONSIT** [comment]
> No, don't bind /tmp the same broken way. /tmp is already bound! Just do the same thing for /var/tmp as is already done for it.

"--bindmount", f"{self.path}:/var/tmp" ?

**Comment by simonlindholm** [comment]
yeah

**Pull request merged**
