### PR TITLE
actually add macros to gcn

### PR DESCRIPTION
**Pull request by EpochFlame**
turns out I added the macros to mac osx last time

### CODE REVIEW

**Comment by EpochFlame** [comment]
to be fair, the macros should work for mac os x just as well

**Comment by EpochFlame** [comment]
huh? this isn’t working in the deployment. do i need to change something else to support the macro?
61D1C85F-A46C-4F2B-8675-A63C771C9664

**Comment by ethteck** [comment]
the backend  doesn't update in the preview deployment. this is just for front-end changes. I'm sure the macro works fine if it works for you locally

**Comment by EpochFlame** [comment]
> the backend doesn't update in the preview deployment. this is just for front-end changes. I'm sure the macro works fine if it works for you locally

understood

**Comment by EpochFlame** [comment]
image
cannot for the life of me figure out why it hates the .fn and .obj macros

**Comment by EpochFlame** [comment]
fixed the escape chars. it works locally now :D

**Comment by EpochFlame** [comment]
image
the macros work. yay

**Review by nanaian — APPROVED** [review]

**Pull request merged**
