### PR TITLE
Copy scratch name to fork

### LINKED ISSUE #175: Use "Untitled fork of (scratch)" for fork name placeholder
Instead of "Untitled scratch".

e.g. a fork of a scratch called "func_123" can placehold to "Untitled fork of func_123"
a fork of an unnamed scratch can just be "Untitled fork"

### PR DESCRIPTION
**Pull request by ethteck**
I think this is an ideal way of tackling #175) as we already know a fork is a fork via the ui. adding "fork of" is just going to get spammy I think

closes #175

### CODE REVIEW

**Review by nanaian — CHANGES_REQUESTED** [review]
Frontend needs to not provide `name` to the fork endpoint for this to work, so please add that (line 277, api.ts). I think this can be done by doing `Object.assign({}, ..., { name: undefined })`

**Comment by nanaian** [comment]
Also the relevant issue does not appear to be #75 but #175

**Comment by ethteck** [comment]
> Frontend needs to not provide `name` to the fork endpoint for this to work, so please add that (line 277, api.ts). I think this can be done by doing `Object.assign({}, ..., { name: undefined })`

how do I gracefully renove name from the result of Object.assign?

**Comment by nanaian** [comment]
`Object.assign({}, scratch, whatever, { name: undefined })` - assign updates with precedence to the right. Or use the `delete` operator.

Thinking about this further it might Just Work without any frontend changes? Please test on the frontend for me :pray:

**Pull request merged**
