### PR TITLE
Remove library suspense...?

### PR DESCRIPTION
**Pull request by ethteck**

### CODE REVIEW

**Comment by ethteck** [comment]
this seems to be working, based on the preview deployment. is it really this simple?

**Comment by roblabla** [comment]
> is it really this simple?

Looks like it. The fix LGTM.

**Comment by nanaian** [comment]
This is cheating, as we should show a loading state or something when `!data`. As a hotfix its fine

**Comment by roblabla** [comment]
> This is cheating, as we should show a loading state or something when !data. As a hotfix its fine

I guess something that could be done is have `useLibraries` return null, and if it does, make the `Select` read-only with a single "Loading" value, or something along those lines

**Comment by ethteck** [comment]
Returning an empty array means we just display the "--" entry if none are loaded. I wasn't able to observe any state where the stuff wasn't loaded. so I'm gonna merge this, but we can enhance it later if we notice any weirdness

**Pull request merged**
